Error fetching token accounts handling
VaultLaboratories/vault-swift pull request #19
Opened 2022-12-20 11:39 UTC by sgrindlay

Following Ant's advice, retry the claim should we run into this error. Have tested and it works successfully on subsequent retry/retries

2022-12-20 11:56 UTC, andyboyd requested changes

2022-12-20 11:56 UTC, andyboyd commented on Sources/vault-swift/Services/ClaimNFTService.swift
> +                    return try await claim(nftBase58: nftBase58, forUserEmailAddress: email, toAppWallet: appWallet, withOtp: otp)
It's never a good idea to write a recursive function with no end condition. If something causes this error to get sent back which will not resolve on a retry (such as some error where the token accounts genuinely don't exist), then this will get stuck in an infinite loop. You'll want to put some kind of maximum retry count on this, possibly with a short delay between retries, similar to the `processClaimWithRetry` function. In fact, it might be an idea to try and genericise that mechanism

2022-12-20 11:59 UTC, sgrindlay commented on Sources/vault-swift/Services/ClaimNFTService.swift
> +                    return try await claim(nftBase58: nftBase58, forUserEmailAddress: email, toAppWallet: appWallet, withOtp: otp)
ah god aye, sorry will sort

2022-12-21 12:46 UTC, ewno approved these changes
Looks good to me - my only suggestion is to make `retryableFunction` a static func on a common helper class/struct so it can be used from other services. Happy if you wanna wait for Andy's review in case he has other suggestions.

2023-01-04 11:44 UTC, andyboyd commented on Sources/vault-swift/Helpers/CommonFunctions.swift
> +    static func retryableFunction(_ function: @escaping () async throws -> String, maxRetries: Int = 5, currentRetries: Int = 0, delay: Int = 2) async throws -> String {
I actually think this might be more appropriate as an extension on `Task`. That way, while it still can't take any parameters, it can at least have whatever return type it needs, rather than only support a String return type like this does.

2023-01-10 10:02 UTC, andyboyd approved these changes

2023-01-10 10:02 UTC, merged